#!/usr/bin/env python3
"""
Interactive configuration helper for Second Brain system.
Run this to set up your Slack credentials.
"""

import os
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent
ENV_FILE = SCRIPTS_DIR / ".env"
ENV_EXAMPLE = SCRIPTS_DIR / ".env.example"


def get_input(prompt: str, example: str) -> str:
    """Get user input with example."""
    print(f"\n{prompt}")
    print(f"Example: {example}")
    value = input("Enter value: ").strip()
    return value


def main():
    print("=" * 60)
    print("  Second Brain - Slack Configuration")
    print("=" * 60)
    print("\nThis will help you set up your Slack credentials.")
    print("You need three values from Slack:\n")

    # Check if .env already exists
    if ENV_FILE.exists():
        print(f"⚠️  {ENV_FILE} already exists.")
        overwrite = input("Overwrite? (y/n): ").strip().lower()
        if overwrite != 'y':
            print("Cancelled.")
            return

    print("\n📝 Let's set up your credentials...\n")

    # Get Slack Bot Token
    print("-" * 60)
    print("1. SLACK BOT TOKEN")
    print("   Go to: https://api.slack.com/apps")
    print("   > Your App > OAuth & Permissions")
    print("   > Copy 'Bot User OAuth Token'")
    bot_token = get_input(
        "Paste your bot token:",
        "xoxb-your-bot-token-here"
    )

    # Get Channel ID
    print("\n" + "-" * 60)
    print("2. SLACK CHANNEL ID")
    print("   In Slack, right-click your #wry_sb channel")
    print("   > View channel details")
    print("   > Scroll to bottom, copy the ID")
    channel_id = get_input(
        "Paste your channel ID:",
        "C0123456789"
    )

    # Get User ID
    print("\n" + "-" * 60)
    print("3. YOUR SLACK USER ID")
    print("   In Slack, click your profile picture")
    print("   > Profile > ... menu > Copy member ID")
    user_id = get_input(
        "Paste your user ID:",
        "U0123456789"
    )

    # Write .env file
    print("\n" + "=" * 60)
    print("Writing configuration...")

    with open(ENV_FILE, "w") as f:
        f.write("# Second Brain System - Environment Variables\n")
        f.write("# Generated by configure.py\n\n")
        f.write(f'export SLACK_BOT_TOKEN="{bot_token}"\n')
        f.write(f'export SLACK_CHANNEL_ID="{channel_id}"\n')
        f.write(f'export SLACK_USER_ID="{user_id}"\n')

    print(f"✅ Configuration saved to: {ENV_FILE}")
    print("\nTo use these credentials, run:")
    print(f"  source {ENV_FILE}")
    print("\nTo test the connection, run:")
    print(f"  cd {SCRIPTS_DIR}")
    print("  source .env && python3 -c \"from slack_client import fetch_messages; print('✅ Connected!', len(fetch_messages()), 'messages')\"")
    print("\n" + "=" * 60)


if __name__ == "__main__":
    main()
